services:

  backend:
    restart: on-failure
    image: dockerbard/porositylab-backend-image:latest
    container_name: backend
    networks:
      - custom_network
    ports:
      - "5000:5000"

  frontend:
    restart: on-failure
    image: dockerbard/porositylab-frontend-image:latest
    container_name: frontend
    networks:
      - custom_network
    ports:
      - "4173:4173"
    
networks:
  custom_network:
    driver: bridge
